config/routes.rb
Dayne::Application.routes.draw do
  post '/register' => 'users#create', :as => :register
  get '/register' => 'users#new', :as => :register
  delete '/delete_user_profile' => 'users#destroy', :as => :delete_user_profile
  get '/edit_user_profile' => 'users#edit', :as => :edit_user_profile
  put '/edit_user_profile' => 'users#update', :as => :edit_user_profile

  post '/login' => 'user_sessions#create', :as => :login
  get '/login' => 'user_sessions#new', :as => :login
  get '/logout' => 'user_sessions#destroy', :as => :logout

  resources :materials
  resources :customers
  resources :salesmen
  resources :material_types
  resources :sales_orders do
    resources :items, controller: :sales_order_items, except: [:index, :show]
  end
  resources :sizes

  root to: 'index#index'

end

app/models/sales_order_item.rb
class SalesOrderItem < ActiveRecord::Base
  attr_accessible :sales_order_id, :sales_order, :material_id, :material, :description, :quantities_attributes
  belongs_to :sales_order
  belongs_to :material
  has_many :quantities, dependent: :destroy
  accepts_nested_attributes_for :quantities, reject_if: lambda { |quantity| quantity['size_id'].blank? or quantity['value'].blank? }, allow_destroy: true

  def total_quantity
    value = 0
    quantities.each do |quantity|
      value += quantity.value
    end
    value
  end

  def possible_materials
    Material.find_all_by_material_type_id(sales_order.material_type_id)
  end

  def possible_sizes
    Size.find_all_by_material_type_id(sales_order.material_type_id)
  end
end

app/controllers/sales_order_items_controller.rb
class SalesOrderItemsController < ApplicationController
  def new
    sales_order = SalesOrder.find(params[:sales_order_id])
    @sales_order_item = SalesOrderItem.new
    @sales_order_item.sales_order = sales_order

    Size.find_all_by_material_type_id(sales_order.material_type_id).each do |size|
      quantity = @sales_order_item.quantities.build
      quantity.size = size
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sales_order_item }
    end
  end

  def edit
    @sales_order_item = SalesOrderItem.find(params[:id])
  end

  def create
    sales_order = SalesOrder.find(params[:sales_order_id])
    @sales_order_item = SalesOrderItem.new(params[:sales_order_item])
    @sales_order_item.sales_order = sales_order

    respond_to do |format|
      if @sales_order_item.save
        format.html { redirect_to @sales_order_item.sales_order, notice: 'Sales order item was successfully created.' }
        format.json { render json: @sales_order_item, status: :created, location: @sales_order_item }
      else
        format.html { render action: "new" }
        format.json { render json: @sales_order_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @sales_order_item = SalesOrderItem.find(params[:id])

    respond_to do |format|
      if @sales_order_item.update_attributes(params[:sales_order_item])
        format.html { redirect_to @sales_order_item.sales_order, notice: 'Sales order item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sales_order_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    sales_order = SalesOrder.find(params[:sales_order_id])
    @sales_order_item = SalesOrderItem.find(params[:id])
    @sales_order_item.destroy

    respond_to do |format|
      format.html { redirect_to sales_order }
      format.json { head :no_content }
    end
  end
end

app/views/sales_order_items/_form.html.erb
<%= form_for @sales_order_item, :html => {:class => "form-horizontal"} do |form| %>
    <%= form_errors_block @sales_order_item %>

    <%= form_input form, @sales_order_item, :material do %>
        <%= form.collection_select :material_id, @sales_order_item.possible_materials, :id, :name %>
    <% end %>

    <%= form_input form, @sales_order_item, :description do %>
        <%= form.text_field :description, class: 'input-xxlarge' %>
    <% end %>

    <%= form.fields_for :quantities do |builder| %>
        <%= render 'quantity_fields', f: builder %>
    <% end %>

    <%= form_submit form do %>
        <%= button_tag(type: 'submit', class: "btn btn-primary", title: 'Save') do %>
            <i class="icon-ok icon-white"></i>
        <% end %>
    <% end %>
<% end %>

app/views/sales_order_items/_quantity_fields.html.erb
<div class="nested-fields">
  <div class="control-group">
    <%= f.label f.object.size.name.to_sym, class: 'control-label' %>
    <div class="controls">
      <%= f.hidden_field :size_id %>
      <%= f.number_field :value %>
      <%= link_to_remove_association 'Remove', f %>
    </div>
  </div>
</div>

app/views/sales_order_items/edit.html.erb
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li><a href="<%= sales_orders_url %>">Sales Orders</a> <span class="divider">/</span></li>
  <li><a href="<%= sales_order_url(@sales_order_item.sales_order) %>">Sales
    Order <%= @sales_order_item.sales_order_id %></a> <span class="divider">/</span></li>
  <li class="active">Edit Sales Order Item</li>
</ul>
<legend>Edit Sales Order Item</legend>
<%= render 'form' %>

app/views/sales_order_items/show.html.erb
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li><a href="<%= sales_orders_url %>">Sales Orders</a> <span class="divider">/</span></li>
  <li class="active">Sales Order <%= @sales_order.id %></li>
</ul>
<legend>Sales Order <%= @sales_order.id %></legend>
<div class="well well-small">
  <dl class="dl-horizontal">
    <dt><%= SalesOrder.human_attribute_name :customer %></dt>
    <dd><%= @sales_order.customer.name %></dd>

    <dt><%= SalesOrder.human_attribute_name :delivery_date %></dt>
    <dd><%= format_date @sales_order.delivery_date %></dd>

    <dt><%= SalesOrder.human_attribute_name :salesman %></dt>
    <dd><%= @sales_order.salesman.name %></dd>

    <dt><%= SalesOrder.human_attribute_name :material_type %></dt>
    <dd><%= @sales_order.material_type.name %></dd>

    <dt><%= SalesOrder.human_attribute_name :total %></dt>
    <dd><%= @sales_order.total_quantity %></dd>

    <dd>
      <div class="btn-group">
          <%= link_to edit_sales_order_path(@sales_order), :class => "btn btn-primary", :title => "Edit Sales Order" do %>
            <i class="icon-pencil icon-white"></i>
        <% end %>
        <%= link_to @sales_order, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => "btn btn-danger", :title => "Delete Sales Order" do %>
            <i class="icon-trash icon-white"></i>
        <% end %>
      </div>
    </dd>
  </dl>
</div>
<legend>Items</legend>
<table class="table table-striped table-hover">
  <thead>
  <tr>
    <th><%= SalesOrderItem.human_attribute_name :material %></th>
    <th><%= SalesOrderItem.human_attribute_name :description %></th>
    <% @sales_order.used_sizes.each do |size| %>
        <th><%= size.name %></th>
    <% end %>
    <th><%= SalesOrderItem.human_attribute_name :total %></th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @sales_order.sales_order_items.each do |item| %>
      <tr>
        <td><%= item.material.name %></td>
        <td><%= item.description %></td>
        <% @sales_order.used_sizes.each do |size| %>
            <td><%= item.quantities.find_by_size_id(size.id).value rescue '-' %></td>
        <% end %>
        <td><%= item.total_quantity %></td>
        <td>
          <div class="btn-group">
            <%= link_to edit_sales_order_item_path(@sales_order), :class => "btn btn-primary", :title => "Edit Sales Order" do %>
                <i class="icon-pencil icon-white"></i>
            <% end %>
            <%= link_to @sales_order, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => "btn btn-danger", :title => "Delete Sales Order" do %>
                <i class="icon-trash icon-white"></i>
            <% end %>
          </div>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>