config/routes.rb
Dayne::Application.routes.draw do
  post '/register' => 'users#create', :as => :register
  get '/register' => 'users#new', :as => :register
  delete '/delete_user_profile' => 'users#destroy', :as => :delete_user_profile
  get '/edit_user_profile' => 'users#edit', :as => :edit_user_profile
  put '/edit_user_profile' => 'users#update', :as => :edit_user_profile

  post '/login' => 'user_sessions#create', :as => :login
  get '/login' => 'user_sessions#new', :as => :login
  get '/logout' => 'user_sessions#destroy', :as => :logout

  resources :materials
  resources :customers
  resources :salesmen
  resources :material_types
  resources :sales_orders do
    resources :items, controller: :sales_order_items, except: [:index, :show]
  end
  resources :sizes

  root to: 'index#index'

end

app/controllers/material_types_controller.rb
class MaterialTypesController < ApplicationController
  # GET /material_types
  # GET /material_types.json
  def index
    @material_types = MaterialType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @material_types }
    end
  end

  # GET /material_types/1
  # GET /material_types/1.json
  def show
    @material_type = MaterialType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @material_type }
    end
  end

  # GET /material_types/new
  # GET /material_types/new.json
  def new
    @material_type = MaterialType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @material_type }
    end
  end

  # GET /material_types/1/edit
  def edit
    @material_type = MaterialType.find(params[:id])
  end

  # POST /material_types
  # POST /material_types.json
  def create
    @material_type = MaterialType.new(params[:material_type])

    respond_to do |format|
      if @material_type.save
        format.html { redirect_to @material_type, notice: 'Material type was successfully created.' }
        format.json { render json: @material_type, status: :created, location: @material_type }
      else
        format.html { render action: "new" }
        format.json { render json: @material_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /material_types/1
  # PUT /material_types/1.json
  def update
    @material_type = MaterialType.find(params[:id])

    respond_to do |format|
      if @material_type.update_attributes(params[:material_type])
        format.html { redirect_to @material_type, notice: 'Material type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @material_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /material_types/1
  # DELETE /material_types/1.json
  def destroy
    @material_type = MaterialType.find(params[:id])
    @material_type.destroy

    respond_to do |format|
      format.html { redirect_to material_types_url }
      format.json { head :no_content }
    end
  end
end

app/views/material_types/_form.html.erb
<%= form_for(@material_type) do |f| %>
    <% if @material_type.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@material_type.errors.count, "error") %> prohibited this material_type from being
            saved:</h2>

          <ul>
            <% @material_type.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %>
      <br/>
      <%= f.text_field :name %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/material_types/edit.html.erb
<h1>Editing material_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @material_type %> |
<%= link_to 'Back', material_types_path %>

app/views/material_types/index.html.erb
<h1>Listing material_types</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @material_types.each do |material_type| %>
      <tr>
        <td><%= material_type.name %></td>
        <td><%= link_to 'Show', material_type %></td>
        <td><%= link_to 'Edit', edit_material_type_path(material_type) %></td>
        <td><%= link_to 'Destroy', material_type, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
</table>

<br/>

<%= link_to 'New Material type', new_material_type_path %>

app/views/material_types/new.html.erb
<h1>New material_type</h1>

<%= render 'form' %>

<%= link_to 'Back', material_types_path %>

app/views/material_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @material_type.name %>
</p>


<%= link_to 'Edit', edit_material_type_path(@material_type) %> |
<%= link_to 'Back', material_types_path %>