config/routes.rb
Dayne::Application.routes.draw do
  post '/register' => 'users#create', :as => :register
  get '/register' => 'users#new', :as => :register
  delete '/delete_user_profile' => 'users#destroy', :as => :delete_user_profile
  get '/edit_user_profile' => 'users#edit', :as => :edit_user_profile
  put '/edit_user_profile' => 'users#update', :as => :edit_user_profile

  post '/login' => 'user_sessions#create', :as => :login
  get '/login' => 'user_sessions#new', :as => :login
  get '/logout' => 'user_sessions#destroy', :as => :logout

  resources :materials
  resources :customers
  resources :salesmen
  resources :material_types
  resources :sales_orders do
    resources :items, controller: :sales_order_items, except: [:index, :show]
  end
  resources :sizes

  root to: 'index#index'

end

app/models/sales_order.rb
class SalesOrder < ActiveRecord::Base
  attr_accessible :customer_id, :customer, :delivery_date, :material_type_id, :material_type, :salesman_id, :salesman
  has_many :sales_order_items, dependent: :destroy
  belongs_to :customer
  belongs_to :salesman
  belongs_to :material_type

  validates_presence_of :delivery_date
  validates_presence_of :customer
  validates_presence_of :material_type

  def total_quantity
    value = 0
    sales_order_items.each do |item|
      value += item.total_quantity unless item.total_quantity.nil?
    end
    value
  end

  def used_sizes
    sizes = Array.new

    sales_order_items.each do |item|
      item.quantities.each do |quantity|
        sizes.append(quantity.size) unless quantity.size.nil?
      end
    end

    sizes.uniq
    sizes.sort_by { |size| size.name }
  end
end

app/controllers/sales_orders_controller.rb
class SalesOrdersController < ApplicationController
  # GET /sales_orders
  # GET /sales_orders.json
  def index
    @sales_orders = SalesOrder.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sales_orders }
    end
  end

  # GET /sales_orders/1
  # GET /sales_orders/1.json
  def show
    @sales_order = SalesOrder.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sales_order }
    end
  end

  # GET /sales_orders/new
  # GET /sales_orders/new.json
  def new
    @sales_order = SalesOrder.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sales_order }
    end
  end

  # GET /sales_orders/1/edit
  def edit
    @sales_order = SalesOrder.find(params[:id])
  end

  # POST /sales_orders
  # POST /sales_orders.json
  def create
    @sales_order = SalesOrder.new(params[:sales_order])

    respond_to do |format|
      if @sales_order.save
        format.html { redirect_to @sales_order, notice: 'Sales order was successfully created.' }
        format.json { render json: @sales_order, status: :created, location: @sales_order }
      else
        format.html { render action: "new" }
        format.json { render json: @sales_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sales_orders/1
  # PUT /sales_orders/1.json
  def update
    @sales_order = SalesOrder.find(params[:id])

    respond_to do |format|
      if @sales_order.update_attributes(params[:sales_order])
        format.html { redirect_to @sales_order, notice: 'Sales order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sales_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales_orders/1
  # DELETE /sales_orders/1.json
  def destroy
    @sales_order = SalesOrder.find(params[:id])
    @sales_order.destroy

    respond_to do |format|
      format.html { redirect_to sales_orders_url }
      format.json { head :no_content }
    end
  end
end

app/views/sales_orders/_form.html.erb
<%= form_for @sales_order, :html => {:class => "form-horizontal"} do |form| %>
    <%= form_errors_block @sales_order %>

    <%= form_input(form, @sales_order, :customer) do %>
        <%= form.collection_select :customer_id, Customer.all, :id, :name %>
    <% end %>

    <%= form_input form, @sales_order, :delivery_date do %>
        <%= datepicker_field :sales_order, @sales_order, :delivery_date %>
    <% end %>

    <%= form_input(form, @sales_order, :salesman) do %>
        <%= form.collection_select :salesman_id, Salesman.all, :id, :name %>
    <% end %>

    <%= form_input(form, @sales_order, :material_type) do %>
        <%= form.collection_select :material_type_id, MaterialType.all, :id, :name %>
    <% end %>

    <%= form_submit form do %>
        <%= button_tag(type: 'submit', class: "btn btn-primary", title: 'Save') do %>
            <i class="icon-ok icon-white"></i>
        <% end %>
    <% end %>
<% end %>

app/views/sales_orders/edit.html.erb
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li><a href="<%= sales_orders_url %>">Sales Orders</a> <span class="divider">/</span></li>
  <li class="active">Edit Sales Order <%= @sales_order.id %></li>
</ul>
<legend>Edit Sales Order <%= @sales_order.id %></legend>
<%= render 'form' %>

app/views/sales_orders/index.html.erb
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">Sales Orders</li>
</ul>
<legend>Sales Orders</legend>
<table class="table table-striped table-hover">
  <thead>
  <tr>
    <th>#</th>
    <th><%= SalesOrder.human_attribute_name :customer %></th>
    <th><%= SalesOrder.human_attribute_name :delivery_date %></th>
    <th><%= SalesOrder.human_attribute_name :salesman %></th>
    <th><%= SalesOrder.human_attribute_name :material_type %></th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @sales_orders.each do |sales_order| %>
      <tr>
        <td><%= link_to sales_order.id, sales_order %></td>
        <td><%= sales_order.customer.name %></td>
        <td><%= format_date sales_order.delivery_date %></td>
        <td><%= sales_order.salesman.name %></td>
        <td><%= sales_order.material_type.name %></td>
        <td>
          <div class="btn-group">
            <%= link_to edit_sales_order_path(sales_order), :class => "btn btn-primary", :title => "Edit Sales Order" do %>
                <i class="icon-pencil icon-white"></i>
            <% end %>
            <%= link_to sales_order, :method => :delete, :data => {:confirm => 'Are you sure?'}, :class => "btn btn-danger", :title => "Delete Sales Order" do %>
                <i class="icon-trash icon-white"></i>
            <% end %>
          </div>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<div class="btn-toolbar">
  <%= link_to new_sales_order_path, :class => "btn btn-primary", :title => "Create Sales Order" do %>
      <i class="icon-plus icon-white"></i>
  <% end %>
</div>

app/views/sales_orders/new.html.erb
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li><a href="<%= sales_orders_url %>">Sales Orders</a> <span class="divider">/</span></li>
  <li class="active">New Sales Order</li>
</ul>
<legend>New Sales Order</legend>
<%= render 'form' %>

app/views/sales_orders/show.html.erb
<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li><a href="<%= sales_orders_url %>">Sales Orders</a> <span class="divider">/</span></li>
  <li class="active">Sales Order <%= @sales_order.id %></li>
</ul>
<legend>Sales Order <%= @sales_order.id %></legend>
<div class="well well-small">
  <dl class="dl-horizontal">
    <dt><%= SalesOrder.human_attribute_name :customer %></dt>
    <dd><%= @sales_order.customer.name %></dd>

    <dt><%= SalesOrder.human_attribute_name :delivery_date %></dt>
    <dd><%= format_date @sales_order.delivery_date %></dd>

    <dt><%= SalesOrder.human_attribute_name :salesman %></dt>
    <dd><%= @sales_order.salesman.name %></dd>

    <dt><%= SalesOrder.human_attribute_name :material_type %></dt>
    <dd><%= @sales_order.material_type.name %></dd>

    <dt><%= SalesOrder.human_attribute_name :total %></dt>
    <dd><%= @sales_order.total_quantity %></dd>

    <dd>
      <div class="btn-group">
        <%= link_to edit_sales_order_path(@sales_order), :class => "btn btn-primary", :title => "Edit Sales Order" do %>
            <i class="icon-pencil icon-white"></i>
        <% end %>
        <%= link_to @sales_order, :method => :delete, :data => {:confirm => 'Are you sure?'}, :class => "btn btn-danger", :title => "Delete Sales Order" do %>
            <i class="icon-trash icon-white"></i>
        <% end %>
      </div>
    </dd>
  </dl>
</div>
<legend>Items</legend>
<table class="table table-striped table-hover">
  <thead>
  <tr>
    <th><%= SalesOrderItem.human_attribute_name :material %></th>
    <th><%= SalesOrderItem.human_attribute_name :description %></th>
    <% @sales_order.used_sizes.each do |size| %>
        <th><%= size.name %></th>
    <% end %>
    <th><%= SalesOrderItem.human_attribute_name :total %></th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @sales_order.sales_order_items.each do |item| %>
      <tr>
        <td><%= item.material.name %></td>
        <td><%= item.description %></td>
        <% @sales_order.used_sizes.each do |size| %>
            <td><%= item.quantities.find_by_size_id(size.id).value rescue '-' %></td>
        <% end %>
        <td><%= item.total_quantity %></td>
        <td>
          <div class="btn-group">
            <%= link_to edit_sales_order_item_path(@sales_order, item), :class => "btn btn-primary", :title => "Edit Sales Order" do %>
                <i class="icon-pencil icon-white"></i>
            <% end %>
            <%= link_to sales_order_item_path(@sales_order, item), :method => :delete, :data => {:confirm => 'Are you sure?'}, :class => "btn btn-danger", :title => "Delete Sales Order" do %>
                <i class="icon-trash icon-white"></i>
            <% end %>
          </div>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<div class="btn-toolbar">
  <%= link_to new_sales_order_item_path(@sales_order), :class => "btn btn-primary", :title => "Create Sales Order" do %>
      <i class="icon-plus icon-white"></i>
  <% end %>
</div>